#!/bin/bash
# 测试文件生成脚本
# 用法: ./generate-test-files.sh [输出目录]

OUTPUT_DIR="${1:-./test-files}"

echo "正在生成测试文件到: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# 清理旧文件
rm -rf "$OUTPUT_DIR"/*

# ==================== 基础测试组 ====================
echo "创建基础测试文件..."

# 1. 基础图片序列（测试序列号、perCategory）- 10个文件
mkdir -p "$OUTPUT_DIR/01-basic-sequence"
touch "$OUTPUT_DIR/01-basic-sequence/IMG_2024_001.jpg"
touch "$OUTPUT_DIR/01-basic-sequence/IMG_2024_002.jpg"
touch "$OUTPUT_DIR/01-basic-sequence/IMG_2024_003.jpg"
touch "$OUTPUT_DIR/01-basic-sequence/IMG_2024_004.jpg"
touch "$OUTPUT_DIR/01-basic-sequence/IMG_2024_005.jpg"
touch "$OUTPUT_DIR/01-basic-sequence/photo_6.png"
touch "$OUTPUT_DIR/01-basic-sequence/photo_7.png"
touch "$OUTPUT_DIR/01-basic-sequence/photo_8.png"
touch "$OUTPUT_DIR/01-basic-sequence/photo_9.png"
touch "$OUTPUT_DIR/01-basic-sequence/photo_10.png"

# 2. 混合扩展名（测试perExtension scope）- 10个文件
mkdir -p "$OUTPUT_DIR/02-mixed-extensions"
touch "$OUTPUT_DIR/02-mixed-extensions/doc1.pdf"
touch "$OUTPUT_DIR/02-mixed-extensions/doc2.docx"
touch "$OUTPUT_DIR/02-mixed-extensions/doc3.pdf"
touch "$OUTPUT_DIR/02-mixed-extensions/doc4.docx"
touch "$OUTPUT_DIR/02-mixed-extensions/sheet1.xlsx"
touch "$OUTPUT_DIR/02-mixed-extensions/sheet2.xls"
touch "$OUTPUT_DIR/02-mixed-extensions/sheet3.xlsx"
touch "$OUTPUT_DIR/02-mixed-extensions/sheet4.xls"
touch "$OUTPUT_DIR/02-mixed-extensions/slides1.pptx"
touch "$OUTPUT_DIR/02-mixed-extensions/slides2.ppt"

# 3. 层级文件夹（测试perFolder scope）- 14个文件
mkdir -p "$OUTPUT_DIR/03-folders/photos/vacation"
mkdir -p "$OUTPUT_DIR/03-folders/photos/family"
mkdir -p "$OUTPUT_DIR/03-folders/photos/travel"
mkdir -p "$OUTPUT_DIR/03-folders/documents/work"
mkdir -p "$OUTPUT_DIR/03-folders/documents/personal"
mkdir -p "$OUTPUT_DIR/03-folders/documents/archive"

touch "$OUTPUT_DIR/03-folders/photos/vacation/beach_01.jpg"
touch "$OUTPUT_DIR/03-folders/photos/vacation/beach_02.jpg"
touch "$OUTPUT_DIR/03-folders/photos/vacation/sunset_01.png"
touch "$OUTPUT_DIR/03-folders/photos/vacation/sunset_02.png"
touch "$OUTPUT_DIR/03-folders/photos/family/birthday_01.jpg"
touch "$OUTPUT_DIR/03-folders/photos/family/birthday_02.jpg"
touch "$OUTPUT_DIR/03-folders/photos/family/christmas_01.png"
touch "$OUTPUT_DIR/03-folders/photos/family/christmas_02.png"
touch "$OUTPUT_DIR/03-folders/photos/travel/tokyo_01.jpg"
touch "$OUTPUT_DIR/03-folders/photos/travel/tokyo_02.jpg"
touch "$OUTPUT_DIR/03-folders/documents/work/report_Q1.pdf"
touch "$OUTPUT_DIR/03-folders/documents/work/report_Q2.pdf"
touch "$OUTPUT_DIR/03-folders/documents/work/invoice_001.xlsx"
touch "$OUTPUT_DIR/03-folders/documents/work/invoice_002.xlsx"
touch "$OUTPUT_DIR/03-folders/documents/personal/resume.pdf"
touch "$OUTPUT_DIR/03-folders/documents/personal/cover_letter.docx"
touch "$OUTPUT_DIR/03-folders/documents/archive/2023_old_report.pdf"
touch "$OUTPUT_DIR/03-folders/documents/archive/2023_backup.xlsx"

# 4. 特殊字符文件名（测试清理规则）- 16个文件
mkdir -p "$OUTPUT_DIR/04-special-chars"
touch "$OUTPUT_DIR/04-special-chars/my file with spaces.txt"
touch "$OUTPUT_DIR/04-special-chars/another file name.txt"
touch "$OUTPUT_DIR/04-special-chars/file-with-dashes.txt"
touch "$OUTPUT_DIR/04-special-chars/file--double--dashes.txt"
touch "$OUTPUT_DIR/04-special-chars/file_with_underscores.txt"
touch "$OUTPUT_DIR/04-special-chars/file__double__underscores.txt"
touch "$OUTPUT_DIR/04-special-chars/file---multiple---dashes.txt"
touch "$OUTPUT_DIR/04-special-chars/file___multiple___underscores.txt"
touch "$OUTPUT_DIR/04-special-chars/   spaces around   .txt"
touch "$OUTPUT_DIR/04-special-chars/  double  spaces  .txt"
touch "$OUTPUT_DIR/04-special-chars/tabs	and	spaces.txt"
touch "$OUTPUT_DIR/04-special-chars/UPPERCASE.TXT"
touch "$OUTPUT_DIR/04-special-chars/lowercase.txt"
touch "$OUTPUT_DIR/04-special-chars/MiXeD CaSe.TxT"
touch "$OUTPUT_DIR/04-special-chars/PascalCase.File.txt"
touch "$OUTPUT_DIR/04-special-chars/camelCaseFile.txt"
touch "$OUTPUT_DIR/04-special-chars/UPPER_CASE_UNDERSCORE.TXT"

# 5. 中文文件名（测试中文处理）- 10个文件
mkdir -p "$OUTPUT_DIR/05-chinese"
touch "$OUTPUT_DIR/05-chinese/我的文档.txt"
touch "$OUTPUT_DIR/05-chinese/照片_001.jpg"
touch "$OUTPUT_DIR/05-chinese/工作汇报.pdf"
touch "$OUTPUT_DIR/05-chinese/2024年总结.docx"
touch "$OUTPUT_DIR/05-chinese/项目文件_final_v2.xlsx"
touch "$OUTPUT_DIR/05-chinese/会议纪要_0315.pdf"
touch "$OUTPUT_DIR/05-chinese/财务报表_Q1.xlsx"
touch "$OUTPUT_DIR/05-chinese/合同_客户A_2024.pdf"
touch "$OUTPUT_DIR/05-chinese/产品说明书_v3.docx"
touch "$OUTPUT_DIR/05-chinese/团队合影_2024春节.jpg"

# 6. 数字提取测试（测试preserveOriginal）- 14个文件
mkdir -p "$OUTPUT_DIR/06-extract-numbers"
touch "$OUTPUT_DIR/06-extract-numbers/item_1.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/item_2.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/item_3.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/item_10.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/item_11.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/item_12.jpg"
touch "$OUTPUT_DIR/06-extract-numbers/photo_2024_005.png"
touch "$OUTPUT_DIR/06-extract-numbers/photo_2023_042.png"
touch "$OUTPUT_DIR/06-extract-numbers/photo_2022_123.png"
touch "$OUTPUT_DIR/06-extract-numbers/photo_2021_999.png"
touch "$OUTPUT_DIR/06-extract-numbers/version_v1.pdf"
touch "$OUTPUT_DIR/06-extract-numbers/version_v2.pdf"
touch "$OUTPUT_DIR/06-extract-numbers/version_v10.pdf"
touch "$OUTPUT_DIR/06-extract-numbers/version_v11.pdf"

# ==================== 场景测试组 ====================
echo "创建场景测试文件..."

# 7. 创作者素材（模拟YouTube/B站UP主）- 14个文件
mkdir -p "$OUTPUT_DIR/07-creator/2024-03-vlog/raw"
mkdir -p "$OUTPUT_DIR/07-creator/2024-03-vlog/exports"
mkdir -p "$OUTPUT_DIR/07-creator/2024-04-travel/raw"
mkdir -p "$OUTPUT_DIR/07-creator/2024-04-travel/exports"
mkdir -p "$OUTPUT_DIR/07-creator/thumbnails"
mkdir -p "$OUTPUT_DIR/07-creator/audio"

touch "$OUTPUT_DIR/07-creator/2024-03-vlog/raw/REC001.mp4"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/raw/REC002.mp4"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/raw/REC003.mp4"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/raw/AUDIO_001.wav"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/raw/AUDIO_002.wav"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/exports/vlog_final_v1.mp4"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/exports/vlog_final_v2.mp4"
touch "$OUTPUT_DIR/07-creator/2024-03-vlog/exports/vlog_final_v3.mp4"
touch "$OUTPUT_DIR/07-creator/2024-04-travel/raw/REC001.mp4"
touch "$OUTPUT_DIR/07-creator/2024-04-travel/raw/REC002.mp4"
touch "$OUTPUT_DIR/07-creator/2024-04-travel/exports/travel_v1.mp4"
touch "$OUTPUT_DIR/07-creator/2024-04-travel/exports/travel_v2.mp4"
touch "$OUTPUT_DIR/07-creator/thumbnails/thumb_01.jpg"
touch "$OUTPUT_DIR/07-creator/thumbnails/thumb_02.jpg"
touch "$OUTPUT_DIR/07-creator/thumbnails/thumb_03.jpg"
touch "$OUTPUT_DIR/07-creator/audio/intro_music.mp3"
touch "$OUTPUT_DIR/07-creator/audio/outro_music.mp3"

# 8. 照片整理（模拟相机/手机导出）- 16个文件
mkdir -p "$OUTPUT_DIR/08-photos/DCIM/100CANON"
mkdir -p "$OUTPUT_DIR/08-photos/DCIM/101CANON"
mkdir -p "$OUTPUT_DIR/08-photos/DCIM/102APPLE"

touch "$OUTPUT_DIR/08-photos/DCIM/100CANON/IMG_1234.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/100CANON/IMG_1235.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/100CANON/IMG_1236.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/100CANON/IMG_1237.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/101CANON/IMG_2001.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/101CANON/IMG_2002.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/101CANON/IMG_2003.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/101CANON/IMG_2004.JPG"
touch "$OUTPUT_DIR/08-photos/DCIM/102APPLE/IMG_5001.HEIC"
touch "$OUTPUT_DIR/08-photos/DCIM/102APPLE/IMG_5002.HEIC"
touch "$OUTPUT_DIR/08-photos/DCIM/102APPLE/IMG_5003.HEIC"
touch "$OUTPUT_DIR/08-photos/screenshot_2024-03-01.png"
touch "$OUTPUT_DIR/08-photos/screenshot_2024-03-02.png"
touch "$OUTPUT_DIR/08-photos/screenshot_2024-03-03.png"
touch "$OUTPUT_DIR/08-photos/screenshot_2024-03-04.png"
touch "$OUTPUT_DIR/08-photos/screenshot_2024-03-05.png"

# 9. 项目资产（设计/开发）- 16个文件
mkdir -p "$OUTPUT_DIR/09-project-assets/icons"
mkdir -p "$OUTPUT_DIR/09-project-assets/images"
mkdir -p "$OUTPUT_DIR/09-project-assets/fonts"
mkdir -p "$OUTPUT_DIR/09-project-assets/styles"

touch "$OUTPUT_DIR/09-project-assets/icons/icon-home.svg"
touch "$OUTPUT_DIR/09-project-assets/icons/icon-user.svg"
touch "$OUTPUT_DIR/09-project-assets/icons/icon-settings.svg"
touch "$OUTPUT_DIR/09-project-assets/icons/icon-search.svg"
touch "$OUTPUT_DIR/09-project-assets/icons/icon-menu.svg"
touch "$OUTPUT_DIR/09-project-assets/images/hero-bg.jpg"
touch "$OUTPUT_DIR/09-project-assets/images/logo-dark.png"
touch "$OUTPUT_DIR/09-project-assets/images/logo-light.png"
touch "$OUTPUT_DIR/09-project-assets/images/banner-01.jpg"
touch "$OUTPUT_DIR/09-project-assets/images/banner-02.jpg"
touch "$OUTPUT_DIR/09-project-assets/fonts/Inter-Regular.woff2"
touch "$OUTPUT_DIR/09-project-assets/fonts/Inter-Bold.woff2"
touch "$OUTPUT_DIR/09-project-assets/fonts/Inter-Medium.woff2"
touch "$OUTPUT_DIR/09-project-assets/fonts/Roboto-Regular.woff2"
touch "$OUTPUT_DIR/09-project-assets/styles/variables.css"
touch "$OUTPUT_DIR/09-project-assets/styles/components.css"

# ==================== 影视刮削/媒体整理测试 ====================
echo "创建影视刮削测试文件..."

# 音乐文件（测试 media. 变量）- 16个文件
mkdir -p "$OUTPUT_DIR/12-media-scraping/music"
touch "$OUTPUT_DIR/12-media-scraping/music/01 - Bohemian Rhapsody.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/02 - Love of My Life.flac"
touch "$OUTPUT_DIR/12-media-scraping/music/03 - We Will Rock You.wav"
touch "$OUTPUT_DIR/12-media-scraping/music/04 - Don't Stop Me Now.m4a"
touch "$OUTPUT_DIR/12-media-scraping/music/05 - Somebody to Love.ogg"
touch "$OUTPUT_DIR/12-media-scraping/music/06 - Under Pressure.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/07 - Radio Ga Ga.flac"
touch "$OUTPUT_DIR/12-media-scraping/music/08 - Another One Bites the Dust.m4a"
touch "$OUTPUT_DIR/12-media-scraping/music/09 - I Want to Break Free.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/10 - We Are the Champions.wav"
touch "$OUTPUT_DIR/12-media-scraping/music/Queen - Greatest Hits - 01.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/Queen - Greatest Hits - 02.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/[1991] Queen - Innuendo - 01.flac"
touch "$OUTPUT_DIR/12-media-scraping/music/[1991] Queen - Innuendo - 02.flac"
touch "$OUTPUT_DIR/12-media-scraping/music/track_01_song_title_artist.mp3"
touch "$OUTPUT_DIR/12-media-scraping/music/track_02_song_title_artist.mp3"

# 影视文件（测试视频整理场景）- 10个文件
mkdir -p "$OUTPUT_DIR/12-media-scraping/movies"
touch "$OUTPUT_DIR/12-media-scraping/movies/Inception.2010.1080p.bluray.x264-[yts].mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/The.Matrix.1999.BluRay.mkv"
touch "$OUTPUT_DIR/12-media-scraping/movies/Interstellar.2014.IMAX.1080p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/The.Dark.Knight.2008.2160p.mkv"
touch "$OUTPUT_DIR/12-media-scraping/movies/Pulp.Fiction.1994.1080p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/Fight.Club.1999.1080p.BluRay.x264-[YTS].mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/Forrest.Gump.1994.2160p.UHD.BluRay.mkv"
touch "$OUTPUT_DIR/12-media-scraping/movies/The.Godfather.1972.1080p.BluRay.x264-[YTS].mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/Django.Unchained.2012.1080p.BluRay.mp4"
touch "$OUTPUT_DIR/12-media-scraping/movies/The.Shawshank.Redemption.1994.2160p.mkv"

# 电视剧/剧集 - 18个文件
mkdir -p "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S01"
mkdir -p "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S02"
mkdir -p "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S03"
mkdir -p "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S01"
mkdir -p "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S02"

touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S01/breaking.bad.s01e01.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S01/breaking.bad.s01e02.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S01/breaking.bad.s01e03.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S01/breaking.bad.s01e04.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S02/breaking.bad.s02e01.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S02/breaking.bad.s02e02.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S02/breaking.bad.s02e03.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S03/breaking.bad.s03e01.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Breaking.Bad/S03/breaking.bad.s03e02.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S01/silicon.valley.s01e01.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S01/silicon.valley.s01e02.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S01/silicon.valley.s01e03.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S01/silicon.valley.s01e04.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S02/silicon.valley.s02e01.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S02/silicon.valley.s02e02.720p.mp4"
touch "$OUTPUT_DIR/12-media-scraping/tv-series/Silicon.Valley/S02/silicon.valley.s02e03.720p.mp4"

# ==================== 边界测试组 ====================
echo "创建边界测试文件..."

# 10. 超长文件名 - 4个文件
mkdir -p "$OUTPUT_DIR/10-edge-cases"
touch "$OUTPUT_DIR/10-edge-cases/this-is-a-very-long-file-name-that-contains-many-words-and-could-be-difficult-to-read-without-proper-formatting.txt"
touch "$OUTPUT_DIR/10-edge-cases/another-extremely-long-file-name-that-has-even-more-words-and-characters-to-test-the-limits-of-file-systems.txt"
touch "$OUTPUT_DIR/10-edge-cases/short.txt"
touch "$OUTPUT_DIR/10-edge-cases/a.txt"

# 11. 无扩展名文件 - 6个文件
touch "$OUTPUT_DIR/10-edge-cases/README"
touch "$OUTPUT_DIR/10-edge-cases/Makefile"
touch "$OUTPUT_DIR/10-edge-cases/.gitignore"
touch "$OUTPUT_DIR/10-edge-cases/LICENSE"
touch "$OUTPUT_DIR/10-edge-cases/CHANGELOG"
touch "$OUTPUT_DIR/10-edge-cases/INSTALL"

# 12. 多扩展名文件 - 6个文件
touch "$OUTPUT_DIR/10-edge-cases/archive.tar.gz"
touch "$OUTPUT_DIR/10-edge-cases/backup.tar.bz2"
touch "$OUTPUT_DIR/10-edge-cases/data.json.bak"
touch "$OUTPUT_DIR/10-edge-cases/data.xml.bak"
touch "$OUTPUT_DIR/10-edge-cases/photo.jpg.backup"
touch "$OUTPUT_DIR/10-edge-cases/config.yml.backup"

# 13. 特殊扩展名（代码文件）- 16个文件
mkdir -p "$OUTPUT_DIR/11-code-files"
touch "$OUTPUT_DIR/11-code-files/main.ts"
touch "$OUTPUT_DIR/11-code-files/utils.ts"
touch "$OUTPUT_DIR/11-code-files/helpers.ts"
touch "$OUTPUT_DIR/11-code-files/types.ts"
touch "$OUTPUT_DIR/11-code-files/utils.js"
touch "$OUTPUT_DIR/11-code-files/app.js"
touch "$OUTPUT_DIR/11-code-files/server.js"
touch "$OUTPUT_DIR/11-code-files/styles.css"
touch "$OUTPUT_DIR/11-code-files/theme.css"
touch "$OUTPUT_DIR/11-code-files/config.json"
touch "$OUTPUT_DIR/11-code-files/package.json"
touch "$OUTPUT_DIR/11-code-files/app.tsx"
touch "$OUTPUT_DIR/11-code-files/component.tsx"
touch "$OUTPUT_DIR/11-code-files/helper.py"
touch "$OUTPUT_DIR/11-code-files/script.sh"
touch "$OUTPUT_DIR/11-code-files/index.html"

# ==================== Landing Page 5大场景截图用文件 ====================
echo "创建Landing Page场景演示文件..."

# 1. 照片管理场景 (Photo Management) - 14个文件
mkdir -p "$OUTPUT_DIR/99-landing-page/01-photo-management"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240115_143022.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240115_143156.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240115_143245.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240115_143356.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240220_102455.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240220_102512.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/IMG_20240220_102601.jpg"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/DSC_0034.NEF"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/DSC_0035.NEF"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/DSC_0036.NEF"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/DSC_0037.NEF"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/screenshot_2024.03.01.png"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/screenshot_2024.03.02.png"
touch "$OUTPUT_DIR/99-landing-page/01-photo-management/screenshot_2024.03.03.png"

# 2. 音乐文件场景 (Music Files) - 10个文件
mkdir -p "$OUTPUT_DIR/99-landing-page/02-music-files"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/01 Bohemian Rhapsody.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/02 love of my life.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/03 we will rock you.flac"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/Track_04_-_Don't_Stop_Me_Now.m4a"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/[queen] somebody to love.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/[1991] These Are the Days of Our Lives.flac"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/Queen - Greatest Hits 2021 - 01.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/Queen - Greatest Hits 2021 - 02.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/track_01_song_title_unknown.mp3"
touch "$OUTPUT_DIR/99-landing-page/02-music-files/track_02_song_title_unknown.mp3"

# 3. 视频整理场景 (Video Organizing) - 18个文件
mkdir -p "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/inception.2010.1080p.bluray.x264-[yts].mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/the.dark.knight.2008.2160p.uhd.bluray-[rarbg].mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/interstellar.2014.imax.1080p.blueray.x265.mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/pulp.fiction.1994.1080p.bluray.x264-[yts].mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/fight.club.1999.1080p.bluray.x264-[yts].mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/forrest.gump.1994.2160p.uhd.bluray.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/the.godfather.1972.1080p.bluray.x264-[yts].mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/movies/django.unchained.2012.1080p.bluray.mp4"

mkdir -p "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s01e01.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s01e02.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s01e03.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s01e04.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s02e01.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s02e02.1080p.web-dl.mkv"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Breaking.Bad/breaking.bad.s02e03.1080p.web-dl.mkv"

mkdir -p "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Silicon.Valley"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Silicon.Valley/silicon.valley.s01e01.720p.mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Silicon.Valley/silicon.valley.s01e02.720p.mp4"
touch "$OUTPUT_DIR/99-landing-page/03-video-organizing/tv-series/Silicon.Valley/silicon.valley.s01e03.720p.mp4"

# 4. 代码项目场景 (Code Project) - 16个文件
mkdir -p "$OUTPUT_DIR/99-landing-page/04-code-project/src/components"
mkdir -p "$OUTPUT_DIR/99-landing-page/04-code-project/src/utils"
mkdir -p "$OUTPUT_DIR/99-landing-page/04-code-project/src/hooks"
mkdir -p "$OUTPUT_DIR/99-landing-page/04-code-project/docs"

touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/components/userProfile.tsx"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/components/NavHeader.tsx"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/components/footer_section.tsx"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/components/SidebarMenu.tsx"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/components/MainContent.tsx"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/utils/APIhelpers.ts"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/utils/data-utils.js"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/utils/stringUtils.ts"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/utils/arrayHelpers.js"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/hooks/useFetchData.ts"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/hooks/useLocalStorage.ts"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/src/hooks/useMediaQuery.ts"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/docs/ReadMe.md"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/docs/API_Documentation_v2.md"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/docs/Setup_Guide.md"
touch "$OUTPUT_DIR/99-landing-page/04-code-project/docs/Contributing.md"

# 5. 文档归档场景 (Document Archive) - 16个文件
mkdir -p "$OUTPUT_DIR/99-landing-page/05-document-archive"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/report final version 2.docx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/Budget Sheet - 2024.xlsx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/Contract_2024-01-15_signed.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/meeting notes jan 20.txt"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/Presentation_v3_FINAL.pptx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/invoice_001_2024_03.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/INVOICE-002-MARCH.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/报销单_张三_2024_02_28.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/财务报告_final_v1.xlsx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/会议纪要_0318_v2.docx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/project proposal V3 final FINAL.docx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/员工手册_2024_修订版.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/training materials v2.pptx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/Q1 review report.docx"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/客户合同_backup_2024.pdf"
touch "$OUTPUT_DIR/99-landing-page/05-document-archive/报销单_李四_2024_03_15.pdf"

# ==================== 通用演示文件 ====================
echo "创建通用演示文件..."

# 基础对比 - 12个文件
mkdir -p "$OUTPUT_DIR/99-demo"
touch "$OUTPUT_DIR/99-demo/IMG_0001.jpg"
touch "$OUTPUT_DIR/99-demo/IMG_0002.jpg"
touch "$OUTPUT_DIR/99-demo/IMG_0003.jpg"
touch "$OUTPUT_DIR/99-demo/IMG_0004.jpg"
touch "$OUTPUT_DIR/99-demo/IMG_0005.jpg"
touch "$OUTPUT_DIR/99-demo/IMG_0006.jpg"
touch "$OUTPUT_DIR/99-demo/DSC_9876.jpg"
touch "$OUTPUT_DIR/99-demo/DSC_9877.jpg"
touch "$OUTPUT_DIR/99-demo/DSC_9878.jpg"
touch "$OUTPUT_DIR/99-demo/DSC_9879.jpg"
touch "$OUTPUT_DIR/99-demo/screenshot_2024-01-01.png"
touch "$OUTPUT_DIR/99-demo/screenshot_2024-01-02.png"

# 层级编号演示 - 12个文件
mkdir -p "$OUTPUT_DIR/99-demo/hierarchical/01-Introduction"
mkdir -p "$OUTPUT_DIR/99-demo/hierarchical/02-Body"
mkdir -p "$OUTPUT_DIR/99-demo/hierarchical/03-Conclusion"
mkdir -p "$OUTPUT_DIR/99-demo/hierarchical/04-Appendix"

touch "$OUTPUT_DIR/99-demo/hierarchical/01-Introduction/slide_01_cover.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/01-Introduction/slide_02_overview.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/01-Introduction/slide_03_agenda.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/02-Body/slide_04_content_a.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/02-Body/slide_05_content_b.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/02-Body/slide_06_content_c.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/02-Body/slide_07_content_d.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/03-Conclusion/slide_08_summary.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/03-Conclusion/slide_09_takeaways.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/03-Conclusion/slide_10_qa.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/04-Appendix/slide_11_refs.png"
touch "$OUTPUT_DIR/99-demo/hierarchical/04-Appendix/slide_12_data.png"

# 统计信息
echo ""
echo "✅ 测试文件生成完成！"
echo ""
echo "文件统计:"
find "$OUTPUT_DIR" -type f | wc -l | xargs echo "  总文件数:"
find "$OUTPUT_DIR" -type d | wc -l | xargs echo "  总文件夹数:"
echo ""
echo "测试场景覆盖:"
echo "  ✓ 01-基础序列号测试 (10文件)"
echo "  ✓ 02-混合扩展名测试 (10文件)"
echo "  ✓ 03-层级文件夹测试 (18文件)"
echo "  ✓ 04-特殊字符清理测试 (17文件)"
echo "  ✓ 05-中文文件名测试 (10文件)"
echo "  ✓ 06-数字提取测试 (14文件)"
echo "  ✓ 07-创作者素材场景 (17文件)"
echo "  ✓ 08-照片整理场景 (16文件)"
echo "  ✓ 09-项目资产场景 (16文件)"
echo "  ✓ 10-边界情况测试 (16文件)"
echo "  ✓ 11-代码文件分类 (16文件)"
echo "  ✓ 12-影视刮削/媒体整理 (44文件)"
echo ""
echo "Landing Page 场景:"
echo "  📷 01-照片管理 (14文件)"
echo "  🎵 02-音乐文件 (10文件)"
echo "  🎬 03-视频整理 (18文件)"
echo "  💻 04-代码项目 (16文件)"
echo "  📄 05-文档归档 (16文件)"
echo ""
echo "通用演示:"
echo "  📂 99-demo (24文件)"
echo ""
echo "总计约 260+ 测试文件"
